spring:
  datasource:
    url: jdbc:mysql://localhost/tb_spider?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
mybatis:
  config-locations: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.ks.spider.entity
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    database: 0
#    password: 6379
#    lettuce:
#      pool:
#        max-active: 100
#        min-idle: 100
